### ISSUE TITLE
Allow broken specs to still resolve as much as possible

### ISSUE THREAD

**Issue by GlennButera** [Rhosys/openapi-resolver.js#11]
### Content & configuration

 OpenAPI definition:
 ```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Swagger Petstore",
    "description": "This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.6"
  },
  "servers": [
    {
      "url": "http://localhost:8088"
    }
  ],
  "paths": {
    "/pet": {
      "post": {
        "summary": "",
        "description": "",
        "tags": [
          "pet"
        ],
        "operationId": "createPet",
        "requestBody": {
          "description": "Pet to create",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "pet",
      "description": "Everything about your Pets",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    }
  ],
  "components": {
    "schemas": {
    }
  }
}
 ```

 OpenAPI Resolver usage:
 ```js
const openApiResolver = require('openapi-resolver');
...
const resolved = await openApiResolver(obj);
 ```

### Is your feature request related to a problem?
There currently is not a way to "continueOnError" like there is in the json-schema-ref-parser library.  This can have some benefits in situations where the goal is to resolve JSON Schema references with a best effort.  For example, here is the code that I use to place the "any" JSON Schema in place of a missing JSON Schema reference (pointer is the "json-pointer" module):
```js
/**
 * Utilizes the openapi-resolver library to handle dereferencing as much as possible.  For references that use an
 * invalid or missing pointer, the "any" schema will be placed where the dereferenced JSON Schema would go.
 * @param {object} obj - The object to dereference
 * @returns {object} - Dereferenced object to the best of the ability of the library and error handling
 */
const dereference = async (obj) => {
  try {
    const resolved = await openApiResolver(obj);

    return resolved;
  } catch (err) {
    const {
      errors = [],
    } = err;

    const allowedErrors = errors.filter((error) => ['MissingPointerError', 'InvalidPointerError'].includes(error.name));

    if (allowedErrors.length !== errors.length) throw err;

    const parsed = err.files.schema;
    allowedErrors.forEach((error) => {
      pointer.set(parsed, pointer.compile(error.path), { type: ['array', 'boolean', 'number', 'object', 'string'] });
    });

    return parsed;
  }
};
```

### Describe the solution you'd like
Some options be added to the library.  One would be an option that would be passed into the options object of json-schema-ref-parser as the "continueOnError" option.  I understand that you are forcing the dereference.circular option to be "ignore", so I'm not asking for the full compliment of options be made available, but some of the options are helpful.  In this case, at least one option that maps to the "continueOnError" option is requested.

**Comment by wparad** [comment]
My current thought is to just catch that error and move on. I could imagine something like this instead:
```js
try {
      // eslint-disable-next-line no-underscore-dangle
      pointer = $refs._resolve($refPath, globallyUniqueFqdnPath, options);
    } catch (error) {
      if (error.type === 'MissingPointerError' || error.type === 'InvalidPointerError') {
        return { value: null, resolutionError: 'InvalidRef', ... maybe additional ref information so it is visible };
      }

      throw error;
    }
```

Any reason to think that would be a bad idea? I'm always cautious of exposing internal details to external callers, that's brittle and when the implementation changes, that is liable to break something.

**Comment by GlennButera** [comment]
I think that maybe this would be altering the intent of how the library wants to handle Open API models, and if you agree I will just close my request as something that will not be done.  The above code snippet ends up with JSON Schemas being `null`, which is not a valid JSON Schema document [according to the spec](https://json-schema.org/draft/2020-12/json-schema-core#section-4.3-2):

> A JSON Schema MUST be an object or a boolean.

**Comment by wparad** [comment]
There's already a "handle errors gracefully" on the next line of the code, it seems when this was rewritten we just missed handling some of the exceptions being thrown from the underlying library, or potentially something changed on that side.  

I didn't mean for the code snippet to be taken as gospel, and if having valid schema is preferrable to none, because that's the expectation in the spec, that it is likely the right answer in any case for the library. I don't recall the handling of what `value: null` does, but I thought it was the context of the schema, and not the schema value itself, as I believe the result of the $ref resolution merges into the existing object. `null` just means, `merge nothing in` rather than `replace the parent object with null`.

If that is the new implementation, I'm assuming this is best long term direction to go.

**Comment by wparad** [comment]
After some internal discussion, we're struggling to understand under what circumstance an invalid ref should be allowed. For now I think the correct result is going to be close this ticket, until we uncover further evidence that a broken $ref still somehow creates a good experience somewhere. Maybe there's more to story you know already and can potentially shed additional light on that. Thanks!
